name: 'Get and Cache Dependencies'
description: "Get the dependencies(via npm) and cache them."
inputs:
  caching:
    description: 'Whether to catch dependencies or not'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        cd section_9_project_01
        npm ci
      shell: bash
